name: expense_tracker
description: "An app for tracking your expenses."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.0
  flutter_native_splash: ^2.3.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_riverpod: ^2.4.4
  riverpod_annotation: ^2.3.1
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0
  flutter_spinkit: ^5.2.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_storage: ^11.5.6
  cloud_firestore: ^4.13.6
  connectivity_plus: ^5.0.2
  go_router: ^13.0.1
  fl_chart: ^0.66.0
  pdf: ^3.10.7
  printing: ^5.11.1
  external_path: ^1.0.3
  csv: ^5.1.1
  permission_handler: ^11.2.0
  open_file: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.6
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

# dart run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21

# dart run flutter_native_splash:create
flutter_native_splash:
  color: "#EF5350"
  image: assets/images/app_icon.png
