// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOGQOdWQVrI8cscVdOwfN5jCeTnHcjr0g',
    appId: '1:37924802634:web:f688d26ad5b6aac0b4d6b3',
    messagingSenderId: '37924802634',
    projectId: 'expense-tracker-8ed1d',
    authDomain: 'expense-tracker-8ed1d.firebaseapp.com',
    storageBucket: 'expense-tracker-8ed1d.appspot.com',
    measurementId: 'G-X7NPNY2ELH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkAy9CO8uad0vapB0MOegzUi78hMkIUjg',
    appId: '1:37924802634:android:f3ed0b756f7250fcb4d6b3',
    messagingSenderId: '37924802634',
    projectId: 'expense-tracker-8ed1d',
    storageBucket: 'expense-tracker-8ed1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoCVhePNM_ihLPatDQB-6eBEg-nRaYc4A',
    appId: '1:37924802634:ios:f99b9ff057a8c809b4d6b3',
    messagingSenderId: '37924802634',
    projectId: 'expense-tracker-8ed1d',
    storageBucket: 'expense-tracker-8ed1d.appspot.com',
    iosBundleId: 'com.setashim155.expenseTracker',
  );
}
